import { Inter } from "next/font/google";
import "./styles/globals.scss";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { CssVarsProvider } from "@mui/material/styles";
import theme from "@/app/styles/theme";
import Providers from "@/app/providers";
import Globals from "@/app/_components/Globals/Globals";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <Globals />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
